- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install ca-certificates and curl
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create keyrings directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Set the correct permissions for the GPG key
  become: true
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to sources list
  become: true
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install required packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present